/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interf;

import connection.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Rashmi Muthisnghe
 */
public class entrollment extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    ResultSet rs1 = null;
    PreparedStatement pst1 = null;
    ResultSet rs2 = null;
    PreparedStatement pst2 = null;
    /**
     * Creates new form entrollment
     */
    public entrollment() {
        initComponents();
        conn = DBConnect.connect();
        fillSubjectCombo();
        generateEID();
        updateTable();
        setdate();
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        //fillStudentCombo();
        
        // size of jfram
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private void setdate(){
        new Thread(new Runnable() {

            public void run() {
              //  throw new UnsupportedOperationException("Not supported yet.");
                
                while(true){
                    
                   Date d=new Date();
                   String date=d.toString();
                   String arr[]=date.split(" ");
                   String dd=arr[5]+"/"+arr[1]+"/"+arr[2];
                   lbldate.setText(dd);
                   
                   lbltime.setText(arr[3]);
                    
                }
            }
        }).start();
    }
    
    private void clear() {
        try{
            TextField_student1.setText("");
            ComboBox_subject.setSelectedItem("-SELECT-");
            ComboBox_grade.setSelectedItem("-SELECT-");
        }
       catch (Exception e) 
        {
            System.out.println(e);
        }
    }
    
    private void updateTable(){
        String sql = "select eNo AS Enrollment_ID, sid as Student_ID, cid AS Class_ID from entrollment";
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            Table_Entrol.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            System.out.println(e);
        }
    }
    
    public void generateEID(){
        try 
        {
            String sql = "SELECT MAX(right(eNo,2)) as s from entrollment";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                if(rs.first()== false){
                    TextField_Entrol.setText("E_00001");
                }
                else{
                    rs.last();
                    int id = rs.getInt(1)+1;
                    String s = String.valueOf(id);
                    int no = s.length();
                    for(int a=0; a<5-no; a++ ){
                       s = "0"+s;
                      
                    }
                    TextField_Entrol.setText("E_"+s);
                }
            }
        } 
        catch (Exception e) 
        {
            System.out.println(e);
        }
    }
    
    private void fillSubjectCombo(){
        String sql = "SELECT * FROM subject";
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                String subject = rs.getString("subject");
                ComboBox_subject.addItem(subject);
            }
        }
        catch(Exception e){
          System.out.print("Exception is trows "+ e);
      }
    }     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextField_student1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ComboBox_subject = new javax.swing.JComboBox<>();
        Button_entroll = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TextField_Entrol = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Entrol = new javax.swing.JTable();
        Button_update = new javax.swing.JButton();
        Button_delete = new javax.swing.JButton();
        TextField_search = new javax.swing.JTextField();
        Button_search = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Button_home = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        List_student = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        List_class = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        ComboBox_grade = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbldate2 = new javax.swing.JLabel();
        lbldate11 = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DMIMS");
        setMinimumSize(new java.awt.Dimension(1385, 754));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Enrollment");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        TextField_student1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_student1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_student1KeyTyped(evt);
            }
        });
        getContentPane().add(TextField_student1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 277, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Subject");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        ComboBox_subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-" }));
        ComboBox_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_subjectActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBox_subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 274, -1));

        Button_entroll.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_entroll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Edit_100px (1).png"))); // NOI18N
        Button_entroll.setText("Enroll");
        Button_entroll.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        Button_entroll.setBorderPainted(false);
        Button_entroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_entrollActionPerformed(evt);
            }
        });
        getContentPane().add(Button_entroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, 397, 51));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Entrollment ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        TextField_Entrol.setEditable(false);
        getContentPane().add(TextField_Entrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 280, -1));

        Table_Entrol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_Entrol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_EntrolMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Entrol);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 196, 691, 310));

        Button_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (2).png"))); // NOI18N
        Button_update.setText("Update");
        Button_update.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        Button_update.setBorderPainted(false);
        Button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_updateActionPerformed(evt);
            }
        });
        getContentPane().add(Button_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 156, 51));

        Button_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete (1).png"))); // NOI18N
        Button_delete.setText("Delete");
        Button_delete.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        Button_delete.setBorderPainted(false);
        Button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(Button_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 550, 151, 51));
        getContentPane().add(TextField_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 460, -1));

        Button_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (4).png"))); // NOI18N
        Button_search.setText("Search");
        Button_search.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        Button_search.setBorderPainted(false);
        Button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_searchActionPerformed(evt);
            }
        });
        getContentPane().add(Button_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 130, 136, 47));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 107, 1310, 10));

        Button_home.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home-icon (1).png"))); // NOI18N
        Button_home.setText("Menu");
        Button_home.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        Button_home.setBorderPainted(false);
        Button_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_homeActionPerformed(evt);
            }
        });
        getContentPane().add(Button_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, 159, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Key_30px.png"))); // NOI18N
        jButton8.setText("Log Out");
        jButton8.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 40, 158, 43));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/US_Dollar_100px_1.png"))); // NOI18N
        jButton1.setText("Payment");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 550, 150, 51));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (1).png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 40, 55, 43));

        List_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                List_studentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(List_student);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 222, 397, 150));

        List_class.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                List_classMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(List_class);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 397, 140));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Grade");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));

        ComboBox_grade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13" }));
        ComboBox_grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_gradeActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBox_grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 274, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 40, 20));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 61, 10));

        lbldate2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbldate2.setForeground(new java.awt.Color(255, 255, 255));
        lbldate2.setText("Date :");
        getContentPane().add(lbldate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        lbldate11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbldate11.setForeground(new java.awt.Color(255, 255, 255));
        lbldate11.setText("Time :");
        getContentPane().add(lbldate11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        lbltime.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbltime.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 140, 30));

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbldate.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 140, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blue-bg (2).jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBox_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_subjectActionPerformed
        

//        fillPlaceCombo();
//        
//        ComboBox_place.removeAllItems();
//        fillPlaceCombo();
    }//GEN-LAST:event_ComboBox_subjectActionPerformed

    private void Button_entrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_entrollActionPerformed
        try
        {  
            String sql = "Insert into entrollment(eNo, sid, cid) values (?,?,?)";
          
            pst = conn.prepareStatement(sql);
            pst.setString(1,TextField_Entrol.getText() );
            pst.setString(2,jLabel5.getText() );
            pst.setString(3,jLabel6.getText() );
          
            
            if(jLabel5.getText().equals("")|| jLabel6.getText().equals("") ){
                JOptionPane.showMessageDialog(null, "Select Class");
            }
            
            else{
                pst.execute();
                JOptionPane.showMessageDialog(null, "Enroll Successful");
                updateTable();
                generateEID();
                clear();    
            }    
         
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_Button_entrollActionPerformed

    private void Table_EntrolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_EntrolMouseClicked
        try{
            int row = Table_Entrol.getSelectedRow();
            String table_click = (Table_Entrol.getModel().getValueAt(row, 0).toString());
            String sql = "select * from entrollment where eNo='"+table_click+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
           
            if(rs.next()){
                String add1 = rs.getString("eNo");
                TextField_Entrol.setText(add1);
               
                try{
                    String add2 = rs.getString("sid");
                    jLabel5.setText(add2);
                    String sql1 = "SELECT `fname`, `mname`, `lname` FROM `student` WHERE `sno`='"+add2+"'";
                pst1 = conn.prepareStatement(sql1);
                rs1 = pst1.executeQuery();
                while(rs1.next()){
                    String n1 = rs1.getString("fname");
                    String n2 = rs1.getString("mname");
                    String n3 = rs1.getString("lname");
                    TextField_student1.setText(n1+" "+n2+" "+n3);
                }
                }catch(Exception e){
                    System.out.println(e);
                }
               
                try{
                    String add3 = rs.getString("cid");
                    jLabel6.setText(add3);
                    String sql2 = "SELECT s.subject, c.grade FROM class c, subject s WHERE s.subNo=c.subject AND c.classNo='"+add3+"'";
                    pst1 = conn.prepareStatement(sql2);
                    rs1 = pst1.executeQuery();
                    while(rs1.next()){
                        String sub = rs1.getString("s.subject");
                        String grade = rs1.getString("c.grade");
                        ComboBox_subject.setSelectedItem(sub);
                        ComboBox_grade.setSelectedItem(grade);
                }
                }catch(Exception e){
                    System.out.println(e);
                }
               
               
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_Table_EntrolMouseClicked

    private void Button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_updateActionPerformed
        int x1 = JOptionPane.showConfirmDialog(null, "Do you want to update this...");
       if(x1==0)
        {
        try{
            
           String value1 = TextField_Entrol.getText();
           String value2 = jLabel5.getText();
           String value3 = jLabel6.getText();
           
           String sql = "update entrollment set sid='"+value2+"', cid='"+value3+"' where eNo='"+value1+"'";
           pst = conn.prepareStatement(sql);
           pst.execute();
           
           JOptionPane.showMessageDialog(null, "Update Successful");
               updateTable();
               generateEID();
               clear();
        }
        catch(Exception e){
            System.out.println(e);
        }
        }
    }//GEN-LAST:event_Button_updateActionPerformed

    private void Button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_deleteActionPerformed
        int x1 = JOptionPane.showConfirmDialog(null, "Do you want to delete this...");
        if(x1==0)
        {
            String sql = "delete from entrollment where eNo=?";

            try{
               pst = conn.prepareStatement(sql);
               pst.setString(1, TextField_Entrol.getText());
               pst.execute();
               JOptionPane.showMessageDialog(null, "Delete Successful");
               updateTable();

               generateEID();
               
                clear();
               
               
            }
            catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_Button_deleteActionPerformed

    private void Button_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_searchActionPerformed
        String s = TextField_search.getText();
        String sql = "SELECT * FROM entrollment WHERE eNo LIKE '%"+s+"%'OR sid LIKE '%"+s+"%' OR cid LIKE '%"+s+"%' ";
        
        try{
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        Table_Entrol.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
          System.out.print("Exception is trows "+ e);
      }
        
    }//GEN-LAST:event_Button_searchActionPerformed

    private void Button_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_homeActionPerformed
        main m = new main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_homeActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        login l = new login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        payment p = new payment();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TextField_student1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_student1KeyTyped
        
    }//GEN-LAST:event_TextField_student1KeyTyped

    private void TextField_student1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_student1KeyReleased
        try{
            String sql = "select * from student where fname like '"+TextField_student1.getText()+"%' or mname like '"+TextField_student1.getText()+"%' or lname like '"+TextField_student1.getText()+"%'";
            Vector v = new Vector();
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                v.add(rs.getString("sno")+" - "+rs.getString("fname")+" "+rs.getString("mname")+" "+rs.getString("lname"));
            }
            List_student.setListData(v);
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_TextField_student1KeyReleased

    private void List_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_studentMouseClicked
        try{
            String s = List_student.getSelectedValue().toString().split("-")[0];
            String sql = "select distinct fname, mname, lname,sno from student where sno='"+s+"'";
            //Vector v = new Vector();
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                TextField_student1.setText(rs.getString("fname")+" "+rs.getString("mname")+" "+rs.getString("lname"));
                jLabel5.setText(rs.getString("sno"));
            }
            
        }
        catch(Exception e){
            System.out.println(e);
        }

    }//GEN-LAST:event_List_studentMouseClicked

    private void ComboBox_gradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_gradeActionPerformed
       try{
            String sql = "SELECT c.classNo, t.fname, t.lname, b.place, c.day, c.stime, c.etime, c.price FROM class c, teacher t, branch b, subject s WHERE t.tno=c.Teacher AND b.bId=c.place AND s.subNo=c.subject AND s.subject='"+ComboBox_subject.getSelectedItem().toString()+"' AND c.grade='"+ComboBox_grade.getSelectedItem().toString()+"'";
            Vector v = new Vector();
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                v.add(rs.getString("c.classNo")+" - "+rs.getString("t.fname")+" "+rs.getString("t.lname")+" - "+rs.getString("b.place")+" - "+rs.getString("c.day")+" - "+rs.getString("c.stime")+" - "+rs.getString("c.etime")+" - "+rs.getString("c.price"));
            }
            List_class.setListData(v);
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_ComboBox_gradeActionPerformed

    private void List_classMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_classMouseClicked
        try{
            String s = List_class.getSelectedValue().toString().split("-")[0];
            String sql = "select classNo from class where classNo='"+s+"'";
            //Vector v = new Vector();
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                jLabel6.setText(rs.getString("classNo"));
            }
            
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_List_classMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entrollment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_delete;
    private javax.swing.JButton Button_entroll;
    private javax.swing.JButton Button_home;
    private javax.swing.JButton Button_search;
    private javax.swing.JButton Button_update;
    private javax.swing.JComboBox<String> ComboBox_grade;
    private javax.swing.JComboBox<String> ComboBox_subject;
    private javax.swing.JList<String> List_class;
    private javax.swing.JList<String> List_student;
    private javax.swing.JTable Table_Entrol;
    private javax.swing.JTextField TextField_Entrol;
    private javax.swing.JTextField TextField_search;
    private javax.swing.JTextField TextField_student1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldate11;
    private javax.swing.JLabel lbldate2;
    private javax.swing.JLabel lbltime;
    // End of variables declaration//GEN-END:variables
}
