/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interf;

import com.toedter.calendar.JCalendar;
import connection.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Month;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Locale;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Rashmi Muthisnghe
 */
public class payment extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form payment
     */
    public payment() {
        initComponents();
        conn = DBConnect.connect();
        generatePaymentID();
        setdate();
        setMonth();
        setdate1();
        
        // size of jfram
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private void setdate1(){
        new Thread(new Runnable() {

            public void run() {
              //  throw new UnsupportedOperationException("Not supported yet.");
                
                while(true){
                    
                   Date d=new Date();
                   String date=d.toString();
                   String arr[]=date.split(" ");
                   String dd=arr[5]+"/"+arr[1]+"/"+arr[2];
                   lbldate.setText(dd);
                   
                   lbltime.setText(arr[3]);
                    
                }
            }
        }).start();
    }
    
    public void clear(){
       TextField_eid.setText("");
       TextField_cid.setText("");
       TextField_sub.setText("");
       TextField_teacher.setText("");
       TextField_pay.setText("");
       
    }
    
    public void generatePaymentID(){
        try 
        {
            String sql = "SELECT MAX(right(pId,2)) as s from payment";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                if(rs.first()== false){
                    TextField_pid.setText("P_00001");
                }
                else{
                    rs.last();
                    int id = rs.getInt(1)+1;
                    String s = String.valueOf(id);
                    int no = s.length();
                    for(int a=0; a<5-no; a++ ){
                       s = "0"+s;
                      
                    }
                    TextField_pid.setText("P_"+s);
                }
            }
        } 
        catch (Exception e) 
        {
            System.out.println(e);
        }
    }
    
    private void setdate(){
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd ");
        Date date = new Date();
        TextField_date.setText(dateFormat.format(date));
    }
    
    private void setMonth(){
        String[] x = new String[]{"January",
                                      "February",            
                                      "March",            
                                      "April",            
                                      "May",            
                                      "June",            
                                      "July",            
                                      "August",            
                                      "September",            
                                      "October",            
                                      "November",            
                                      "December",}; 
        int month;
        GregorianCalendar date = new GregorianCalendar();      
        month = date.get(Calendar.MONTH);
       // month = month+1;
        String y = x[month];
        TextField_mon.setText(y);
       // System.out.println("Current month is  " + y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextField_sname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        List_sdata = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        List_cdata = new javax.swing.JList<>();
        Button_pay = new javax.swing.JButton();
        Button_home1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TextField_date = new javax.swing.JTextField();
        TextField_eid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TextField_mon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TextField_pid = new javax.swing.JTextField();
        TextField_cid = new javax.swing.JTextField();
        TextField_pay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextField_teacher = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TextField_sub = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        Button_PaymentDetails = new javax.swing.JButton();
        lbldate2 = new javax.swing.JLabel();
        lbldate11 = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DMIMS");
        setMinimumSize(new java.awt.Dimension(1385, 754));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Payment");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (4).png"))); // NOI18N
        jLabel3.setText("Search using name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));

        TextField_sname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_snameKeyReleased(evt);
            }
        });
        getContentPane().add(TextField_sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, 440, -1));

        List_sdata.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        List_sdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                List_sdataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(List_sdata);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 330, -1));

        List_cdata.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        List_cdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                List_cdataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(List_cdata);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, 350, -1));

        Button_pay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_pay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/payment1.png"))); // NOI18N
        Button_pay.setText("Pay");
        Button_pay.setToolTipText("Make Payment");
        Button_pay.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        Button_pay.setBorderPainted(false);
        Button_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_payActionPerformed(evt);
            }
        });
        getContentPane().add(Button_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 660, 154, 40));

        Button_home1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home-icon (1).png"))); // NOI18N
        Button_home1.setText("Menu");
        Button_home1.setToolTipText("Go to Menu");
        Button_home1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        Button_home1.setBorderPainted(false);
        Button_home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_home1ActionPerformed(evt);
            }
        });
        getContentPane().add(Button_home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 50, 140, 50));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Key_30px.png"))); // NOI18N
        jButton8.setText("Log Out");
        jButton8.setToolTipText("Log Out");
        jButton8.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 50, 134, 49));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 120, 1313, 10));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Student Name");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 140, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Class Details");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 240, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextField_date.setEditable(false);
        jPanel1.add(TextField_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 190, -1));

        TextField_eid.setEditable(false);
        jPanel1.add(TextField_eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 190, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        TextField_mon.setEditable(false);
        jPanel1.add(TextField_mon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 190, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Teacher");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Class ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Payment ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Payment");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, -1, -1));

        TextField_pid.setEditable(false);
        jPanel1.add(TextField_pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 190, -1));

        TextField_cid.setEditable(false);
        jPanel1.add(TextField_cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 190, -1));

        TextField_pay.setEditable(false);
        jPanel1.add(TextField_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, 190, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Subject");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Entrollment ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        TextField_teacher.setEditable(false);
        jPanel1.add(TextField_teacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 190, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Month");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        TextField_sub.setEditable(false);
        jPanel1.add(TextField_sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 190, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blue-bg (2).jpg"))); // NOI18N
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 465, 1180, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (1).png"))); // NOI18N
        jButton2.setToolTipText("Close This");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 50, 43, 49));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/te-illustration-bill-pay.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 350, 260));

        Button_PaymentDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_PaymentDetails.setText("View Payment Details");
        Button_PaymentDetails.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        Button_PaymentDetails.setBorderPainted(false);
        Button_PaymentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PaymentDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(Button_PaymentDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 660, 190, 40));

        lbldate2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbldate2.setForeground(new java.awt.Color(255, 255, 255));
        lbldate2.setText("Date :");
        getContentPane().add(lbldate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        lbldate11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbldate11.setForeground(new java.awt.Color(255, 255, 255));
        lbldate11.setText("Time :");
        getContentPane().add(lbldate11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        lbltime.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbltime.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 140, 30));

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbldate.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 140, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blue-bg (2).jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 1390, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void TextField_snameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_snameKeyReleased
        try{
            String sql = "select * from student where fname like '"+TextField_sname.getText()+"%' or mname like '"+TextField_sname.getText()+"%' or lname like '"+TextField_sname.getText()+"%'";
            Vector v = new Vector();
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                v.add(rs.getString("sno")+" - "+rs.getString("fname")+" "+rs.getString("mname")+" "+rs.getString("lname"));
            }
            List_sdata.setListData(v);
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_TextField_snameKeyReleased

    private void List_sdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_sdataMouseClicked
        try{
            String s = List_sdata.getSelectedValue().toString().split("-")[0];
            String sql = "select distinct e.eNo, c.classNo, sub.subject from student s, entrollment e, class c, subject sub where s.sno=e.sid and e.cid=c.classNo and sub.subNo=c.subject and s.sno='"+s+"'";
            Vector v = new Vector();
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                v.add(rs.getString("e.eNo")+" - "+rs.getString("c.classNo")+" - "+rs.getString("sub.subject"));
            }
            List_cdata.setListData(v);
        }
        catch(Exception e){
            System.out.println(e);
        }


    }//GEN-LAST:event_List_sdataMouseClicked

    private void List_cdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_cdataMouseClicked
        try{
            String s = List_cdata.getSelectedValue().toString().split("-")[0];
            String sql = "SELECT e.cid, e.eNo, sub.subject,t.fname, t.lname, c.price FROM entrollment e, subject sub, class c, teacher t WHERE sub.subNo=c.subject AND c.classNo=e.cid AND t.tno=c.Teacher AND e.eNo='"+s+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                TextField_eid.setText(rs.getString("e.eNo"));
                TextField_cid.setText(rs.getString("e.cid"));
                TextField_sub.setText(rs.getString("sub.subject"));
                TextField_teacher.setText(rs.getString("t.fname")+" "+rs.getString("t.lname"));
                TextField_pay.setText(rs.getString("c.price"));
                
            }
            System.out.println(s);
        }
        catch (Exception e){
            System.out.println(e);
        }     
    }//GEN-LAST:event_List_cdataMouseClicked

    private void Button_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_payActionPerformed

        try{
           
            String sql = "insert into payment(pId, eId, month, price, date) values('"+TextField_pid.getText()+"', '"+TextField_eid.getText()+"', '"+TextField_mon.getText()+"', '"+TextField_pay.getText()+"', '"+TextField_date.getText()+"')";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Payment Done!");
            clear();
            generatePaymentID();
        }
        catch (Exception e){
            System.out.println(e);
        }
        

    }//GEN-LAST:event_Button_payActionPerformed

    private void Button_home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_home1ActionPerformed
        main m = new main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_home1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        login l = new login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Button_PaymentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PaymentDetailsActionPerformed
        paymentDetails pd = new paymentDetails();
        pd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_PaymentDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_PaymentDetails;
    private javax.swing.JButton Button_home1;
    private javax.swing.JButton Button_pay;
    private javax.swing.JList<String> List_cdata;
    private javax.swing.JList<String> List_sdata;
    private javax.swing.JTextField TextField_cid;
    private javax.swing.JTextField TextField_date;
    private javax.swing.JTextField TextField_eid;
    private javax.swing.JTextField TextField_mon;
    private javax.swing.JTextField TextField_pay;
    private javax.swing.JTextField TextField_pid;
    private javax.swing.JTextField TextField_sname;
    private javax.swing.JTextField TextField_sub;
    private javax.swing.JTextField TextField_teacher;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldate11;
    private javax.swing.JLabel lbldate2;
    private javax.swing.JLabel lbltime;
    // End of variables declaration//GEN-END:variables
}
