/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interf;

import com.googlecode.javacv.OpenCVFrameGrabber;
import com.googlecode.javacv.cpp.opencv_core;
import static com.googlecode.javacv.cpp.opencv_highgui.cvSaveImage;
import connection.DBConnect;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.PrinterJob;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import org.opencv.core.Core;

/**
 *
 * @author Rashmi Muthisnghe
 */
public class studentdetailsU extends javax.swing.JFrame {
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
   
    /**
     * Creates new form studentdetails
     */
    public studentdetailsU() {
        initComponents();
        conn = DBConnect.connect();
        generateStudentID();
        updateTable();
        setdate();
        
        dob.getJCalendar().setMaxSelectableDate(new Date());
        
        // size of jfram
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private void setdate(){
        new Thread(new Runnable() {

            public void run() {
              //  throw new UnsupportedOperationException("Not supported yet.");
                
                while(true){
                    
                   Date d=new Date();
                   String date=d.toString();
                   String arr[]=date.split(" ");
                   String dd=arr[5]+"/"+arr[1]+"/"+arr[2];
                   lbldate.setText(dd);
                   
                   lbltime.setText(arr[3]);
                    
                }
            }
        }).start();
    }
    
    public void clear(){
        fname.setText("");
        mname.setText("");
        lname.setText("");
        dob.setDate(null);
        TextArea_address.setText("");
        tel.setText("");
        mob.setText("");
    }
    
    public void star(){
        jLabel13.setVisible(true);
        jLabel15.setVisible(true);
        jLabel16.setVisible(true);
        jLabel20.setVisible(true);
        TextArea_address.setVisible(true);
        //jLabel24.setVisible(true);
        jLabel14.setVisible(true);
    }
    
    private void updateTable(){
        String sql = "select sno AS ID, CONCAT(fname,' ',mname,' ',lname) AS Name, dob AS Date_Of_Birth, address AS Address, tp AS Telephon_No, mp AS Mobile_No from student";
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            Table_student.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            System.out.println(e);
        }
    }
    
     public void generateStudentID(){
        try 
        {
            
            String sql = "SELECT MAX(right(sno,2)) as s from student";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                if(rs.first()== false){
                    sid.setText("S_00001");
                }
                else{
                    rs.last();
                    int id = rs.getInt(1)+1;
                    String s = String.valueOf(id);
                    int no = s.length();
                    for(int a=0; a<5-no; a++ ){
                       s = "0"+s;
                      
                    }
                    sid.setText("S_"+s);
                }
            }
        } 
        catch (Exception e) 
        {
            System.out.println(e);
        }
         
    }
     
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        lname = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        sid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mob = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Button_save = new javax.swing.JButton();
        Button_update = new javax.swing.JButton();
        Button_Delete = new javax.swing.JButton();
        Text_search = new javax.swing.JTextField();
        Button_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_student = new javax.swing.JTable();
        Button_home = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea_address = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lbldate2 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lbldate11 = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DMIMS");
        setMinimumSize(new java.awt.Dimension(1385, 754));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Student ID");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 99, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("First Name");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 99, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Middle Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 99, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Last Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 99, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DOB");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, 64, -1));

        dob.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 120, 250, -1));
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 253, -1));
        getContentPane().add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 253, -1));

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 253, -1));

        sid.setEditable(false);
        sid.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 253, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Telephone");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 160, 99, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mobile");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 200, 99, -1));

        mob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobKeyTyped(evt);
            }
        });
        getContentPane().add(mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 200, 253, -1));

        tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telKeyTyped(evt);
            }
        });
        getContentPane().add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 160, 253, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("STUDENT");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 240, 95, -1));

        Button_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (3).png"))); // NOI18N
        Button_save.setText("Save");
        Button_save.setToolTipText("Save Student Details");
        Button_save.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), java.awt.Color.white));
        Button_save.setBorderPainted(false);
        Button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_saveActionPerformed(evt);
            }
        });
        getContentPane().add(Button_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 146, 53));

        Button_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (2).png"))); // NOI18N
        Button_update.setText("Update");
        Button_update.setToolTipText("Update Student Details");
        Button_update.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), java.awt.Color.white));
        Button_update.setBorderPainted(false);
        Button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_updateActionPerformed(evt);
            }
        });
        getContentPane().add(Button_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 146, 53));

        Button_Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete (1).png"))); // NOI18N
        Button_Delete.setText("Delete");
        Button_Delete.setToolTipText("Delete Student Details");
        Button_Delete.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), java.awt.Color.white));
        Button_Delete.setBorderPainted(false);
        Button_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 146, 53));

        Text_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_searchActionPerformed(evt);
            }
        });
        Text_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Text_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Text_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Text_searchKeyTyped(evt);
            }
        });
        getContentPane().add(Text_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 210, -1));

        Button_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (4).png"))); // NOI18N
        Button_search.setText("Search");
        Button_search.setToolTipText("Search Student Details");
        Button_search.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), java.awt.Color.white));
        Button_search.setBorderPainted(false);
        Button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_searchActionPerformed(evt);
            }
        });
        getContentPane().add(Button_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 146, 53));

        Table_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Middle Name", "Last Name", "Date Of Birth", "Address", "Telephone No", "Mobile No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_student.setToolTipText("Student Table");
        Table_student.setAutoscrolls(false);
        Table_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_studentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_student);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 1250, 190));

        Button_home.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home-icon (1).png"))); // NOI18N
        Button_home.setText("Menu");
        Button_home.setToolTipText("Go to menu");
        Button_home.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), java.awt.Color.white));
        Button_home.setBorderPainted(false);
        Button_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_homeActionPerformed(evt);
            }
        });
        getContentPane().add(Button_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 146, 53));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 1320, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1320, 10));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("*");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 160, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("*");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 120, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("*");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 160, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("*");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 200, -1, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Key_30px.png"))); // NOI18N
        jButton8.setText("Log Out");
        jButton8.setToolTipText("Go to login form");
        jButton8.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), java.awt.Color.white));
        jButton8.setBorderPainted(false);
        jButton8.setMaximumSize(new java.awt.Dimension(87, 45));
        jButton8.setMinimumSize(new java.awt.Dimension(87, 45));
        jButton8.setPreferredSize(new java.awt.Dimension(87, 45));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1103, 11, 146, 53));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Edit_100px (1).png"))); // NOI18N
        jButton1.setText("Enroll to Classes");
        jButton1.setToolTipText("Enroll to Classes");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), java.awt.Color.white));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 410, 210, 53));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (1).png"))); // NOI18N
        jButton2.setToolTipText("Close this");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), java.awt.Color.white));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 11, 53, 53));

        TextArea_address.setColumns(20);
        TextArea_address.setRows(5);
        jScrollPane2.setViewportView(TextArea_address);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 240, 253, 120));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("*");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 250, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/students-at-school (1).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 320, 230));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer (1).png"))); // NOI18N
        jButton3.setText("Print ");
        jButton3.setToolTipText("Print Registration Form");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 146, 53));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loading-hi (1).png"))); // NOI18N
        jButton4.setText("Table Load");
        jButton4.setToolTipText("Table Load");
        jButton4.setAutoscrolls(true);
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 410, 146, 53));

        lbldate2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbldate2.setForeground(new java.awt.Color(255, 255, 255));
        lbldate2.setText("Date :");
        getContentPane().add(lbldate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbldate.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 140, 30));

        lbldate11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbldate11.setForeground(new java.awt.Color(255, 255, 255));
        lbldate11.setText("Time :");
        getContentPane().add(lbldate11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        lbltime.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbltime.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 140, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blue-bg (2).jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_saveActionPerformed
        if(fname.getText().equals("")){
            jLabel13.setVisible(true);
        }else{
            jLabel13.setVisible(false);
        }
        
//        if(mname.getText().equals("")){
//            jLabel24.setVisible(true);
//        }else{
//            jLabel24.setVisible(false);
//        }
        
        if(lname.getText().equals("")){
            jLabel15.setVisible(true);
        }else{
            jLabel15.setVisible(false);
        }
        
        if(dob.getDate().equals("")){
            jLabel15.setVisible(true);
        }else{
            jLabel15.setVisible(false);
        }
        
        if(tel.getText().equals("")){
            jLabel20.setVisible(true);
        }else{
            jLabel20.setVisible(false);
        }
        
        if(mob.getText().equals("")){
            jLabel14.setVisible(true);
        }else{
            jLabel14.setVisible(false);
        }
        
        if(TextArea_address.getText().equals("")){
            jLabel19.setVisible(true);
        }else{
            jLabel19.setVisible(false);
        }
        
               
        try
        {
            Date d = dob.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String x =sdf.format(d);
            if(fname.getText().equals("") || lname.getText().equals("") || dob.getDate().equals("") || tel.getText().equals("") || TextArea_address.getText().equals("") || mob.getText().equals("")  )
            {
                JOptionPane.showMessageDialog(null,"Error, Please check and then re-enter ");
            }
            else{
          String sql = "Insert into student(sno, fname, mname, lname, dob, address, tp, mp) values (?,?,?,?,?,?,?,?)";
          
          pst = conn.prepareStatement(sql);
          pst.setString(1,sid.getText() );
          pst.setString(2,fname.getText() );
          pst.setString(3,mname.getText() );
          pst.setString(4,lname.getText() );
          pst.setString(5,x );
          pst.setString(6,TextArea_address.getText() );
          pst.setString(7,tel.getText() );
          pst.setString(8,mob.getText() );
          
          pst.execute();
          
          JOptionPane.showMessageDialog(null, "Save Successful");
                updateTable();
                generateStudentID();
                clear();
                star();
            }      
                
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_Button_saveActionPerformed

    private void Button_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DeleteActionPerformed
        int x1 = JOptionPane.showConfirmDialog(null, "Do you want to delete this...");
        if(x1==0)
        {
            String sql = "delete from student where sno=?";

            try{
               pst = conn.prepareStatement(sql);
               pst.setString(1, sid.getText());
               pst.execute();
               JOptionPane.showMessageDialog(null, "Delete Successful");
               updateTable();

               generateStudentID();
               clear();
               star();
               
            }
            catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_Button_DeleteActionPerformed

    private void Table_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_studentMouseClicked
        try{
           int row = Table_student.getSelectedRow();
           String table_click = (Table_student.getModel().getValueAt(row, 0).toString());
           String sql = "select * from student where sno='"+table_click+"'";
           pst = conn.prepareStatement(sql);
           rs = pst.executeQuery();
           
           if(rs.next()){
               String add1 = rs.getString("sno");
               sid.setText(add1);
               String add2 = rs.getString("fname");
               fname.setText(add2);
               String add3 = rs.getString("mname");
               mname.setText(add3);
               String add4 = rs.getString("lname");
               lname.setText(add4);
               Date add5 = rs.getDate("dob");
               dob.setDate(add5);
               String add6 = rs.getString("address");
               TextArea_address.setText(add6);
               String add7 = rs.getString("tp");
               tel.setText(add7);
               String add8 = rs.getString("mp");
               mob.setText(add8);
             
           }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_Table_studentMouseClicked

    private void Button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_updateActionPerformed
       int x1 = JOptionPane.showConfirmDialog(null, "Do you want to update this...");
       if(x1==0)
        {
        try{
            
           String value1 = sid.getText();
           String value2 = fname.getText();
           String value3 = mname.getText();
           String value4 = lname.getText();
           String value5 = ((JTextField)dob.getDateEditor().getUiComponent()).getText();
           String value6 = TextArea_address.getText();
           String value7 = tel.getText();
           String value8 = mob.getText();
          
           String sql = "update student set fname='"+value2+"', mname='"+value3+"', lname='"+value4+"', dob='"+value5+"', address='"+value6+"', tp='"+value7+"', mp='"+value8+"' where sno='"+value1+"'";
           pst = conn.prepareStatement(sql);
           pst.execute();
           
           JOptionPane.showMessageDialog(null, "Update Successful");
               updateTable();

               generateStudentID();
               clear();
               star();
        }
        catch(Exception e){
            System.out.println(e);
        }
        }
    }//GEN-LAST:event_Button_updateActionPerformed

    private void Text_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_searchKeyTyped
        
    }//GEN-LAST:event_Text_searchKeyTyped

    private void Text_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_searchKeyReleased
       
    }//GEN-LAST:event_Text_searchKeyReleased

    private void Text_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_searchKeyPressed
        
    }//GEN-LAST:event_Text_searchKeyPressed

    private void Button_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_searchActionPerformed

        String s = Text_search.getText();
        String sql = "SELECT sno AS ID, CONCAT(fname,' ',mname,' ',lname) AS Name, dob AS Date_Of_Birth, address AS Address, tp AS Telephon_No, mp AS Mobile_No FROM student WHERE sno LIKE '%"+s+"%'OR fname LIKE '"+s+"%' OR lname LIKE '"+s+"%'  ";
        
        try{
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        Table_student.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
          System.out.print("Exception is trows "+ e);
      }
        
    }//GEN-LAST:event_Button_searchActionPerformed

    private void Button_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_homeActionPerformed
        mainU m = new mainU();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_homeActionPerformed

    private void telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telKeyTyped
        char caracter = evt.getKeyChar();
                if (((caracter < '0') || (caracter > '9'))
                        && (caracter != '\b')) {
                    evt.consume();
                     Toolkit.getDefaultToolkit().beep();
                     JOptionPane.showMessageDialog(rootPane, "Cannot Input Characters!");
                }
                if (tel.getText().length() == 10 ){ // limit textfield to 10 characters
            evt.consume(); 
           
                 } 
    }//GEN-LAST:event_telKeyTyped

    private void mobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobKeyTyped
        char caracter = evt.getKeyChar();
                if (((caracter < '0') || (caracter > '9'))
                        && (caracter != '\b')) {
                    evt.consume();
                     Toolkit.getDefaultToolkit().beep();
                     JOptionPane.showMessageDialog(rootPane, "Cannot Input Characters!");
                }
                if (mob.getText().length() == 10 ){ // limit textfield to 10 characters
            evt.consume(); 
           
                 } 
    }//GEN-LAST:event_mobKeyTyped

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        login l = new login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        entrollmentU e = new entrollmentU();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Text_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_searchActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        studentID si = new studentID();
        si.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        updateTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentdetailsU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentdetailsU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentdetailsU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentdetailsU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentdetailsU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Delete;
    private javax.swing.JButton Button_home;
    private javax.swing.JButton Button_save;
    private javax.swing.JButton Button_search;
    private javax.swing.JButton Button_update;
    private javax.swing.JTable Table_student;
    private javax.swing.JTextArea TextArea_address;
    private javax.swing.JTextField Text_search;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldate11;
    private javax.swing.JLabel lbldate2;
    private javax.swing.JLabel lbltime;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField mob;
    private javax.swing.JTextField sid;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
