/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interf;

import com.googlecode.javacv.OpenCVFrameGrabber;
import com.googlecode.javacv.cpp.opencv_core;
import static com.googlecode.javacv.cpp.opencv_highgui.cvSaveImage;
import connection.DBConnect;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Rashmi Muthisnghe
 */
public class teacherU extends javax.swing.JFrame {
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    ResultSet rs1 = null;
    PreparedStatement pst1 = null;
    
    /**
     * Creates new form teacher
     */
    public teacherU() {
        initComponents();
        conn = DBConnect.connect();
        generateStudentID();
        updateTable();
        fillcombo();
        setdate();
        dob.getJCalendar().setMaxSelectableDate(new Date());
        Label_subid.setVisible(false);
        
        // size of jfram
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private void setdate(){
        new Thread(new Runnable() {

            public void run() {
              //  throw new UnsupportedOperationException("Not supported yet.");
                
                while(true){
                    
                   Date d=new Date();
                   String date=d.toString();
                   String arr[]=date.split(" ");
                   String dd=arr[5]+"/"+arr[1]+"/"+arr[2];
                   lbldate.setText(dd);
                   
                   lbltime.setText(arr[3]);
                    
                }
            }
        }).start();
    }
    
    private void fillcombo(){
        String sql = "SELECT * FROM subject";
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                String subject = rs.getString("subject");
                ComboBox_subject.addItem(subject);
            }
        }
        catch(Exception e){
          System.out.print("Exception is trows "+ e);
        }
    }
   
        
    public void clear(){
        fname.setText("");
        lname.setText("");
        nic.setText("");
        ComboBox_subject.setSelectedItem("-SELECT-");
        dob.setDate(null);
        address.setText("");
        tel.setText("");
        mob.setText("");
        email.setText("");
        
    }
    
    private void updateTable(){
        String sql = "select tno AS ID, CONCAT(fname,' ',lname) AS Name, nic AS NIC, subject AS Subject, dob AS DOB, address AS Address, tp AS Telephone_No, mp AS Mobile_No, email AS Email from teacher";
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            Table_student.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            System.out.println(e);
        }
    }
    public void generateStudentID(){
        try 
        {
            String sql = "SELECT MAX(right(tno,2)) as s from teacher";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                if(rs.first()== false){
                    sid.setText("T_00001");
                }
                else{
                    rs.last();
                    int id = rs.getInt(1)+1;
                    String s = String.valueOf(id);
                    int no = s.length();
                    for(int a=0; a<5-no; a++ ){
                       s = "0"+s;
                      
                    }
                    sid.setText("T_"+s);
                }
            }            
        } 
        catch (Exception e) 
        {
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mob = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_student = new javax.swing.JTable();
        Button_save = new javax.swing.JButton();
        Button_update = new javax.swing.JButton();
        Button_Delete = new javax.swing.JButton();
        Text_search = new javax.swing.JTextField();
        Button_search = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        ComboBox_subject = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        Button_home = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Label_subid = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lbldate2 = new javax.swing.JLabel();
        lbldate11 = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DMIMS");
        setMinimumSize(new java.awt.Dimension(1385, 754));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TEACHER");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Teacher ID");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 99, -1));

        sid.setEditable(false);
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 253, -1));
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 253, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Firse Name");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 99, -1));
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 253, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Last Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 99, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DOB");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 95, -1));

        dob.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 130, 253, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, 95, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Telephone");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, 99, -1));

        tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telKeyTyped(evt);
            }
        });
        getContentPane().add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 253, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mobile");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 99, -1));

        mob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobKeyTyped(evt);
            }
        });
        getContentPane().add(mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 210, 253, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 250, 253, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Email");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 99, -1));

        Table_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_student.setToolTipText("Teacher Details");
        Table_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_studentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_student);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 537, 1280, 180));

        Button_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (3).png"))); // NOI18N
        Button_save.setText("Save");
        Button_save.setToolTipText("Save Teacher Details");
        Button_save.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        Button_save.setBorderPainted(false);
        Button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_saveActionPerformed(evt);
            }
        });
        getContentPane().add(Button_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 146, 53));

        Button_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (2).png"))); // NOI18N
        Button_update.setText("Update");
        Button_update.setToolTipText("Update Teacher Details");
        Button_update.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        Button_update.setBorderPainted(false);
        Button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_updateActionPerformed(evt);
            }
        });
        getContentPane().add(Button_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 146, 53));

        Button_Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete (1).png"))); // NOI18N
        Button_Delete.setText("Delete");
        Button_Delete.setToolTipText("Delete Teacher Details");
        Button_Delete.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        Button_Delete.setBorderPainted(false);
        Button_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 146, 53));

        Text_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_searchActionPerformed(evt);
            }
        });
        Text_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Text_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Text_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Text_searchKeyTyped(evt);
            }
        });
        getContentPane().add(Text_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 210, -1));

        Button_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (4).png"))); // NOI18N
        Button_search.setText("Search");
        Button_search.setToolTipText("Search Teacher Details");
        Button_search.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        Button_search.setBorderPainted(false);
        Button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_searchActionPerformed(evt);
            }
        });
        getContentPane().add(Button_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 146, 53));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Subject");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 99, -1));

        ComboBox_subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-" }));
        ComboBox_subject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBox_subjectMouseClicked(evt);
            }
        });
        ComboBox_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_subjectActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBox_subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 253, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 1290, 10));

        Button_home.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home-icon (1).png"))); // NOI18N
        Button_home.setText("Menu");
        Button_home.setToolTipText("Go to main menu");
        Button_home.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        Button_home.setBorderPainted(false);
        Button_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_homeActionPerformed(evt);
            }
        });
        getContentPane().add(Button_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, 146, 53));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Key_30px.png"))); // NOI18N
        jButton8.setText("Log Out");
        jButton8.setToolTipText("Log Out");
        jButton8.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 146, 53));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 1290, 10));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add (1).png"))); // NOI18N
        jButton1.setToolTipText("Add New Subject");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 40, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a (1).png"))); // NOI18N
        jButton2.setToolTipText("Close This");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 20, 53, 53));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("*");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("*");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 250, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("*");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 210, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("*");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 170, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("*");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 130, -1, -1));
        getContentPane().add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 253, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("*");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, -1, 20));
        getContentPane().add(Label_subid, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 280, 82, 13));

        address.setColumns(20);
        address.setRows(5);
        jScrollPane2.setViewportView(address);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 290, 253, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("*");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 300, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/teacher-at-smartboard (2).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 320, 280));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NIC");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, 20));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Time_100px.png"))); // NOI18N
        jButton3.setText(" Class Scheduler");
        jButton3.setToolTipText("Add class");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 440, 250, 53));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loading-hi (1).png"))); // NOI18N
        jButton4.setText("Table Load");
        jButton4.setToolTipText("Table Load");
        jButton4.setAutoscrolls(true);
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 146, 53));

        lbldate2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbldate2.setForeground(new java.awt.Color(255, 255, 255));
        lbldate2.setText("Date :");
        getContentPane().add(lbldate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lbldate11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbldate11.setForeground(new java.awt.Color(255, 255, 255));
        lbldate11.setText("Time :");
        getContentPane().add(lbldate11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        lbltime.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbltime.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 140, 30));

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbldate.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 140, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blue-bg (2).jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1550, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Table_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_studentMouseClicked
        try{
            int row = Table_student.getSelectedRow();
            String table_click = (Table_student.getModel().getValueAt(row, 0).toString());
            String sql = "select * from teacher where tno='"+table_click+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if(rs.next()){
                String add1 = rs.getString("tno");
                sid.setText(add1);
                String add2 = rs.getString("fname");
                fname.setText(add2);
                String add3 = rs.getString("lname");
                lname.setText(add3);
                String add4 = rs.getString("nic");
                nic.setText(add4);
                
                Date add5 = rs.getDate("dob");
                dob.setDate(add5);
                String add9 = rs.getString("address");
                address.setText(add9);
                String add10 = rs.getString("tp");
                tel.setText(add10);
                String add11 = rs.getString("mp");
                mob.setText(add11);
                String add12 = rs.getString("email");
                email.setText(add12);
                                
                try{
                String add13 = rs.getString("subject");
                Label_subid.setText(add13);
                String sql1 = "SELECT * FROM `subject` WHERE `subNo`='"+add13+"'";
                pst1 = conn.prepareStatement(sql1);
                rs1 = pst1.executeQuery();
                while(rs1.next()){
                    String sub = rs1.getString("subject");
                    ComboBox_subject.setSelectedItem(sub);
                }
                }catch(Exception e){
                    System.out.println(e);
                }
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_Table_studentMouseClicked

    private void Button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_saveActionPerformed
        if(fname.getText().equals("")){
            jLabel16.setVisible(true);
        }else{
            jLabel16.setVisible(false);
        }
                       
        if(lname.getText().equals("")){
            jLabel14.setVisible(true);
        }else{
            jLabel14.setVisible(false);
        }
        
        String nic_pattern = "^[0-9]{9}[vVxX]$";
            Pattern pattern1 = Pattern.compile(nic_pattern);
            Matcher regexMatcher1 = pattern1.matcher(nic.getText());
            if(!regexMatcher1.matches()){
                jLabel15.setVisible(true); 
                JOptionPane.showMessageDialog(null,"Invalid NIC number");
            }else{
                jLabel15.setVisible(false);
            }
        
        
        
        if(dob.getDate().equals("")){
            jLabel23.setVisible(true);
        }else{
            jLabel23.setVisible(false);
        }
        
        if(tel.getText().equals("")){
            jLabel22.setVisible(true);
        }else{
            jLabel22.setVisible(false);
        }
        
        if(mob.getText().equals("")){
            jLabel21.setVisible(true);
        }else{
            jLabel21.setVisible(false);
        }
        
        String email_pattern = "^\\w+[\\w-\\.]*\\@\\w+((-\\w+)|(\\w*))\\.[a-z]{2,3}$";
            Pattern pattern = Pattern.compile(email_pattern);
            Matcher regexMatcher = pattern.matcher(email.getText());
            if(!regexMatcher.matches()){
                jLabel20.setVisible(true); 
                JOptionPane.showMessageDialog(null,"Invalid email address");
            }else{
                jLabel20.setVisible(false);
            }
                       
        if(address.getText().equals("")){
            jLabel24.setVisible(true);
        }else{
            jLabel24.setVisible(false);
        }
        try
        {
            Date d = dob.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String x =sdf.format(d);
            
            if(fname.getText().equals("") || lname.getText().equals("") || dob.getDate().equals("") || tel.getText().equals("") || mob.getText().equals("") || address.getText().equals("") || ComboBox_subject.getSelectedItem().equals("SELECT") || !regexMatcher.matches() || !regexMatcher1.matches())
            {
                JOptionPane.showMessageDialog(null,"Error, Please check and then re-enter ");
            }
            else{
                String sql = "Insert into teacher(tno, fname, lname,nic,subject, dob, address, tp, mp, email) values (?,?,?,?,?,?,?,?,?,?)";

                pst = conn.prepareStatement(sql);
                pst.setString(1,sid.getText() );
                pst.setString(2,fname.getText() );
                pst.setString(3,lname.getText() );
                pst.setString(4,nic.getText() );
                pst.setString(5, Label_subid.getText());
                pst.setString(6,x );
                pst.setString(7,address.getText() );
                pst.setString(8,tel.getText() );
                pst.setString(9,mob.getText() );
                pst.setString(10,email.getText() );
                
                pst.execute();

                JOptionPane.showMessageDialog(null, "Save Successful");
                updateTable();
                generateStudentID();
                clear();
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_Button_saveActionPerformed

    private void Button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_updateActionPerformed
        if(fname.getText().equals("")){
            jLabel16.setVisible(true);
        }else{
            jLabel16.setVisible(false);
        }
                        
        if(lname.getText().equals("")){
            jLabel14.setVisible(true);
        }else{
            jLabel14.setVisible(false);
        }
        
        String nic_pattern = "^[0-9]{9}[vVxX]$";
            Pattern pattern1 = Pattern.compile(nic_pattern);
            Matcher regexMatcher1 = pattern1.matcher(nic.getText());
            if(!regexMatcher1.matches()){
                jLabel15.setVisible(true); 
                JOptionPane.showMessageDialog(null,"Invalid NIC number");
            }else{
                jLabel15.setVisible(false);
            }
        
                
        if(dob.getDate().equals("")){
            jLabel23.setVisible(true);
        }else{
            jLabel23.setVisible(false);
        }
        
        if(tel.getText().equals("")){
            jLabel22.setVisible(true);
        }else{
            jLabel22.setVisible(false);
        }
        
        if(mob.getText().equals("")){
            jLabel21.setVisible(true);
        }else{
            jLabel21.setVisible(false);
        }
        
        String email_pattern = "^\\w+[\\w-\\.]*\\@\\w+((-\\w+)|(\\w*))\\.[a-z]{2,3}$";
            Pattern pattern = Pattern.compile(email_pattern);
            Matcher regexMatcher = pattern.matcher(email.getText());
            if(!regexMatcher.matches()){
                jLabel20.setVisible(true); 
                JOptionPane.showMessageDialog(null,"Invalid email address");
            }else{
                jLabel20.setVisible(false);
            }
                       
        if(address.getText().equals("")){
            jLabel24.setVisible(true);
        }else{
            jLabel24.setVisible(false);
        }
        
        int x1 = JOptionPane.showConfirmDialog(null, "Do you want to update this...");
        if(x1==0)
        {
            try{

                String value1 = sid.getText();
                String value2 = fname.getText();
                String value3 = nic.getText();
                String value4 = lname.getText();
                String value14 = Label_subid.getText();
                String value5 = ((JTextField)dob.getDateEditor().getUiComponent()).getText();
                String value9 = address.getText();
                String value10 = tel.getText();
                String value11 = mob.getText();
                String value12 = email.getText();
              
                if(fname.getText().equals("") || lname.getText().equals("") || dob.getDate().equals("") || tel.getText().equals("") || mob.getText().equals("") || address.getText().equals("") || ComboBox_subject.getSelectedItem().equals("SELECT") || !regexMatcher.matches() || !regexMatcher1.matches())
                {
                    JOptionPane.showMessageDialog(null,"Error, Please check and then re-enter ");
                }
                else{
                    String sql = "update teacher set fname='"+value2+"', nic='"+value3+"', lname='"+value4+"',subject='"+value14+"', dob='"+value5+"', address='"+value9+"', tp='"+value10+"', mp='"+value11+"', email='"+value12+"' where tno='"+value1+"'";
                    pst = conn.prepareStatement(sql);
                    pst.execute();

                    JOptionPane.showMessageDialog(null, "Update Successful");
                    updateTable();

                    generateStudentID();
                    clear();
                }
            }
            catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_Button_updateActionPerformed

    private void Button_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DeleteActionPerformed
        int x1 = JOptionPane.showConfirmDialog(null, "Do you want to delete this...");
        if(x1==0)
        {
            String sql = "delete from teacher where tno=?";

            try{
                pst = conn.prepareStatement(sql);
                pst.setString(1, sid.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Delete Successful");
                updateTable();

                generateStudentID();
                clear();

            }
            catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_Button_DeleteActionPerformed

    private void Text_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_searchKeyPressed

    }//GEN-LAST:event_Text_searchKeyPressed

    private void Text_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_searchKeyReleased

    }//GEN-LAST:event_Text_searchKeyReleased

    private void Text_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_searchKeyTyped

    }//GEN-LAST:event_Text_searchKeyTyped

    private void Button_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_searchActionPerformed
        
        String s = Text_search.getText();
        
        try{
            String sql = "SELECT tno AS ID, CONCAT(fname,' ',lname) AS Name, nic AS NIC, subject AS Subject, dob AS DOB, address AS Address, tp AS Telephone_No, mp AS Mobile_No, email AS Email FROM teacher WHERE tno LIKE '%"+s+"%' OR fname LIKE '"+s+"%' OR lname LIKE '"+s+"%' OR subject LIKE '"+s+"%' ";              
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            Table_student.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e){
            System.out.println("OK");
            System.out.print("Exception is trows "+ e);
        }
        

    }//GEN-LAST:event_Button_searchActionPerformed

    private void Button_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_homeActionPerformed
        mainU m = new mainU();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_homeActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        login l = new login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        subjectU s = new subjectU();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))&& (caracter != '\b')) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Cannot Input Characters!");
        }
        if (tel.getText().length() == 10 ){ // limit textfield to 10 characters
            evt.consume(); 
        } 
    }//GEN-LAST:event_telKeyTyped

    private void mobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))&& (caracter != '\b')) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Cannot Input Characters!");
        }
        if (mob.getText().length() == 10 ){ // limit textfield to 10 characters
            evt.consume(); 
        } 
    }//GEN-LAST:event_mobKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ComboBox_subjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBox_subjectMouseClicked
        
        
    }//GEN-LAST:event_ComboBox_subjectMouseClicked

    private void Text_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_searchActionPerformed

    private void ComboBox_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_subjectActionPerformed
        String sub = ComboBox_subject.getSelectedItem().toString();
        String sql = "SELECT `subNo` FROM `subject` WHERE subject='"+sub+"' ";
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                String id = rs.getString("subNo");
                Label_subid.setText(id);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(teacherU.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ComboBox_subjectActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        classShedualU c = new classShedualU();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        updateTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Delete;
    private javax.swing.JButton Button_home;
    private javax.swing.JButton Button_save;
    private javax.swing.JButton Button_search;
    private javax.swing.JButton Button_update;
    private javax.swing.JComboBox<String> ComboBox_subject;
    private javax.swing.JLabel Label_subid;
    private javax.swing.JTable Table_student;
    private javax.swing.JTextField Text_search;
    private javax.swing.JTextArea address;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldate11;
    private javax.swing.JLabel lbldate2;
    private javax.swing.JLabel lbltime;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mob;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField sid;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
